version: '3.8'

services:
  service:
    container_name: ds-service-template
    image: ds-service
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env

  prometheus:
    container_name: prometheus_instance
    image: base_prometheus
    build:
      context: ./prometheus/
      dockerfile: ./Dockerfile
    ports:
      - 9090:9090

  jaeger:
    container_name: jaeger_instance
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
      - 4317:4317
      - 4318:4318
    expose:
      - 6831
